apiVersion: v1
kind: Deployment
metadata:
  name: online-inference-rolling-update
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: online-inference-deployment
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference
          image: vlamelni/online_inference:v3 # test1
          ports:
            - containerPort: 12000