apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:  
  containers:
    - name: online-inference
      image: vlamelni/online_inference:v3 # test2
      imagePullPolicy: "Always"
      ports:
        - containerPort: 12000
      readinessProbe:
        tcpSocket:
          port: 12000
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 12000
        initialDelaySeconds: 5
        periodSeconds: 60
        failureThreshold: 1