path_input_data: "data/preprocessed/heart_cleveland_upload.csv"
output_model_path: "models/"
metric_path: "reports/metrics/"
path_train_features: "data/preprocessed/train_features.csv"
path_test_features: "data/preprocessed/test_features.csv"
path_train_target: "data/preprocessed/train_target.csv"
path_test_target: "data/preprocessed/test_target.csv"
split_parameters:
  size_val: 0.15
  random_state: 42
train_parameters:
  model_type: "LogisticRegression"
  random_state: 42
use_mlflow: False
feature_parameters:
  categorical_features:
    - "sex"
    - "chest pain"
    - "fasting blood sugar"
    - "resting electrocardiographic results"
    - "exercise induced angina"
    - "slope"
    - "number of major vessels"
    - "thal"
  numerical_features:
    - "age"
    - "resting blood pressure"
    - "cholesterol"
    - "max heart rate"
    - "oldpeak"
  target_column: "condition"
  use_logarithm_trick: False
